# Generated by Django 3.2.6 on 2023-10-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='permanent_token',
            new_name='token',
        ),
    ]
